### ISSUE TITLE
no method 'getDate'

### ISSUE THREAD

**Issue by terinjokes** [lyconic/fullcalendar.viewmore#1]
If I use `$("#calendar").limitEvents(4);` I get an error:

```
 Uncaught TypeError: Object 1297400400000 has no method 'getDate'
```

in fullcalendar.js line 4490

**Comment by alassek** [comment]
We currently depend on [DateJS](http://www.datejs.com/) for date-parsing. You're getting that error because you aren't loading it.

**Comment by terinjokes** [comment]
Whoops! Sorry I missed that. Perhaps you should update the Readme to say that.

**Comment by alassek** [comment]
Yeah, the README needs some love. I'll make the dependencies more obvious.
