### ISSUE TITLE
Allow plugin user to choose the event handler of the "view more" button.

### ISSUE THREAD

**Issue by sgreenfield** [lyconic/fullcalendar.viewmore#3]
Allow plugin user to choose the event handler of the "view more" button.  The options values should be "overlay", "agenda view", or a user supplied function.

**Comment by terinjokes** [comment]
**Ignore Me!** Commenting so that I can watch this issue.

**Comment by sgreenfield** [comment]
I have solved this issue.  See bottom of the Readme for an example.  Let me know if you have any problems implementing this.  Thanks.
